apiVersion: v2
name: redirector
version: 0.0.2
description: Manage your HTTP redirects declaratively
keywords:
  - redirect
  - kubernetes
home: https://github.com/chilledornaments/redirector
maintainers:
  - name: Mitchell
