{{ if .Values.config.enabled }}
kind: ConfigMap
apiVersion: v1

metadata:
  name: {{ .Values.config.configMapName }}
  namespace: {{ .Release.Namespace }}

data:
  config.yml: |
    {{ b64dec .Values.config.encodedFileContents | nindent 4 }}

{{ end}}
