name: Redirector Release
on:
  release:
    types: [published]

env:
  CONTAINER_REPOSITORY: ghcr.io/chilledornaments/redirector

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push image to Docker Hub
        run: |
          docker build . \
          --tag ${{env.CONTAINER_REPOSITORY}}:${{github.sha}} \
          --tag ${{env.CONTAINER_REPOSITORY}}:${{github.event.release.tag_name}} \
          --tag ${{env.CONTAINER_REPOSITORY}}:latest
          
          doker push \
          ${{env.CONTAINER_REPOSITORY}}:${{github.sha}} \ 
          ${{env.CONTAINER_REPOSITORY}}:${{github.event.release.tag_name}} \
          ${{env.CONTAINER_REPOSITORY}}:latest
