name: Test suite

on:
  pull_request:
    branches:
      - main
    paths:
      - '*.go'
      - './fixtures/**'
      - .github/workflows/**

env:
  DOCKER_TAG: chilledornaments/redirector

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.24'

      - name: Vet
        run: |
          go vet -race

      - name: Unit tests
        run: |
          go test -v --tags unit_test ./...

  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.24'

      - name: start minikube
        uses: medyagh/setup-minikube@5e71d7574bcbd0a3b04e7263b9cc4b47e2645bfb
        id: minikube
        with:
          cache: true
          minikube-version: 1.36.0
          driver: docker
          container-runtime: containerd
          kubernetes-version: v1.31.0
          cni: bridge
          addons: registry,ingress
          extra-config: 'kubelet.max-pods=10'
          wait: false

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Build with Docker
        run: |
          docker build . --tag ${{env.DOCKER_TAG}}:${{github.sha}}
          
          minikube image load ${{env.DOCKER_TAG}}:${{github.sha}}

      - name: Generate ingress definition
        id: generate
        env:
          KUBE_NAMESPACE: test
        run: |
          CONFIG_PATH=./fixtures/rules.yml go run -v ./... generate -out test-ingress.yml -namespace ${{env.KUBE_NAMESPACE}}
          
          echo "ingress_manifest=test-ingress.yml" >> $GITHUB_OUTPUT
          echo "kube_namespace=${{env.KUBE_NAMESPACE}}" >> $GITHUB_OUTPUT

      - name: Install helm
        uses: azure/setup-helm@v4.3.0

      - name: Create Kubernetes resources
        run: |
          helm upgrade --install redirector-test ./charts/ \
          --namespace ${{steps.generate.outputs.kube_namespace}} \
          --create-namespace \
          --values ./fixtures/kube/values-kube-test.yml \
          --set config.encodedFileContents="$(cat ./fixtures/rules.yml | base64)" \
          --set deploy.image=chilledornaments/redirector:466a1dd6240bcf77154e83a274d397801a6bc5e5
          
  
          kubectl apply -f ${{ steps.generate.outputs.ingress_manifest }}

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Kubernetes integration tests
        run: |
          pip install -r tests/integration/requirements.txt
          
          URL_HOST=$(minikube ip) pytest -v -s tests/integration/

      - name: Load tests
        run: |
          go test -v --tags load_test ./...
